"""Generate VCP stock data and charts for the web viewer."""

import json
import shutil
from pathlib import Path

from tightzone.screener import Screener
from tightzone.charting import fetch_price_history

def main():
    """Generate VCP stock data and charts."""
    print("Fetching VCP stocks...")
    screener = Screener(market="america", apply_vcp_filter=True)
    stocks = screener.scan()

    print(f"Found {len(stocks)} VCP stocks")

    # Charts directory (charts will be generated by React app using client-side libraries)
    charts_dir = Path("charts")

    # Prepare data for web app
    print("Fetching price history for stocks...")
    web_data = []
    for i, stock in enumerate(stocks, 1):
        symbol = stock.get("symbol", "")
        print(f"  [{i}/{len(stocks)}] {symbol}")

        # Fetch price history
        price_history = []
        try:
            history = fetch_price_history(symbol, period="6mo", interval="1d")
            price_history = [
                {
                    "date": bar.timestamp.isoformat(),
                    "close": bar.close,
                    "volume": bar.volume,
                }
                for bar in history
            ]
        except Exception as e:
            print(f"    Warning: Could not fetch history for {symbol}: {e}")

        web_data.append({
            "symbol": symbol,
            "name": stock.get("name"),
            "close": stock.get("close"),
            "volume": stock.get("volume"),
            "marketCap": stock.get("market_cap_basic"),
            "beta": stock.get("beta_1_year"),
            "perfWeek": stock.get("Perf.W"),
            "perfMonth": stock.get("Perf.1M"),
            "perfYear": stock.get("Perf.Y"),
            "sma200": stock.get("SMA200"),
            "priceHistory": price_history,
        })

    # Save data file
    web_dir = Path("web/vcp-viewer/public")
    web_dir.mkdir(parents=True, exist_ok=True)

    data_file = web_dir / "vcp_stocks.json"
    with open(data_file, "w") as f:
        json.dump(web_data, f, indent=2)

    print(f"Saved {len(web_data)} stocks with price history to {data_file}")

    print("\nDone! You can now run the React app:")
    print("  cd web/vcp-viewer")
    print("  npm start")


if __name__ == "__main__":
    main()
