"""Generate VCP stock data and charts for the web viewer."""

import json
import shutil
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed

from tightzone.screener import Screener
from tightzone.charting import fetch_price_history


def fetch_stock_data(stock, index, total):
    """Fetch price history for a single stock."""
    symbol = stock.get("symbol", "")
    print(f"  [{index}/{total}] {symbol}")

    # Fetch price history (3mo for faster performance)
    price_history = []
    try:
        history = fetch_price_history(symbol, period="3mo", interval="1d")
        price_history = [
            {
                "date": bar.timestamp.isoformat(),
                "close": bar.close,
                "volume": bar.volume,
            }
            for bar in history
        ]
    except Exception as e:
        print(f"    Warning: Could not fetch history for {symbol}: {e}")

    return {
        "symbol": symbol,
        "name": stock.get("name"),
        "close": stock.get("close"),
        "volume": stock.get("volume"),
        "marketCap": stock.get("market_cap_basic"),
        "beta": stock.get("beta_1_year"),
        "perfWeek": stock.get("Perf.W"),
        "perfMonth": stock.get("Perf.1M"),
        "perfYear": stock.get("Perf.Y"),
        "sma200": stock.get("SMA200"),
        "priceHistory": price_history,
    }


def main():
    """Generate VCP stock data and charts."""
    print("Fetching VCP stocks...")
    screener = Screener(market="america", apply_vcp_filter=True)
    stocks = screener.scan()

    print(f"Found {len(stocks)} VCP stocks")

    # Charts directory (charts will be generated by React app using client-side libraries)
    charts_dir = Path("charts")

    # Prepare data for web app - use parallel processing for speed
    print("Fetching price history for stocks (in parallel)...")
    web_data = []

    # Use ThreadPoolExecutor to fetch data in parallel (max 15 concurrent requests)
    with ThreadPoolExecutor(max_workers=15) as executor:
        # Submit all tasks
        futures = {
            executor.submit(fetch_stock_data, stock, i, len(stocks)): stock
            for i, stock in enumerate(stocks, 1)
        }

        # Collect results as they complete
        for future in as_completed(futures):
            try:
                stock_data = future.result()
                web_data.append(stock_data)
            except Exception as e:
                stock = futures[future]
                symbol = stock.get("symbol", "unknown")
                print(f"    Error processing {symbol}: {e}")

    # Save data file
    web_dir = Path("web/vcp-viewer/public")
    web_dir.mkdir(parents=True, exist_ok=True)

    data_file = web_dir / "vcp_stocks.json"
    with open(data_file, "w") as f:
        json.dump(web_data, f, indent=2)

    print(f"Saved {len(web_data)} stocks with price history to {data_file}")

    print("\nDone! You can now run the React app:")
    print("  cd web/vcp-viewer")
    print("  npm start")


if __name__ == "__main__":
    main()
